name: example
on: pull_request
jobs:
  comment:
    name: Add checkout and pull commands
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wamburu/comment-on-pr@1.0.1-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: template.md
